version: '3.8'

services:
  servicio1:
    build: ./servicio1
    ports:
      - "5002:5000"
    networks:
      - app-network

  servicio2:
    build: ./servicio2
    ports:
      - "5001:5000"
    networks:
      - app-network

networks:
  app-network: